import cafeLatte from "../components/images/bread.jpeg";
import vanillaLatte from "../components/images/burger.jpeg";
import caramelLatte from "../components/images/coffee-cup.jpeg";
import cinnamonLatte from "../components/images/coffee.jpg";

const Menu_list = [
    // Hot-Coffee
    [
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 11,
            name: "Cafe Latte",
            // imgsrc: require("../components/images/bread.jpeg"),
            imgsrc: cafeLatte,
            price_s: 110,
            price_m: 130,
            price_l: 150,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 12,
            name: "Vanilla Latte",
            // imgsrc: require("../components/images/burger.jpeg"),
            imgsrc: vanillaLatte,
            price_s: 125,
            price_m: 145,
            price_l: 165,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 13,
            name: "Caramel Latte",
            // imgsrc: require("../components/images/coffee-cup.jpeg"),
            imgsrc: caramelLatte,
            price_s: 125,
            price_m: 145,
            price_l: 165,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 14,
            name: "Cinnamon Latte",
            // imgsrc: require("../components/images/coffee.jpg"),
            imgsrc: cinnamonLatte,
            price_s: 125,
            price_m: 145,
            price_l: 165,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 15,
            name: "Vanilla Cappuccino",
            // imgsrc: require("../components/images/fingers.jpg"),
            price_s: 120,
            price_m: 140,
            price_l: 140,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 16,
            name: "Cappuccino",
            // imgsrc: require("../components/images/kutlet.jpg"),
            price_s: 100,
            price_m: 120,
            price_l: 140,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 17,
            name: "Cappuccino Caramel",
            // imgsrc: require("../components/images/momos.jpg"),
            price_s: 120,
            price_m: 140,
            price_l: 160,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 18,
            name: "Cappuccino Cinnamon",
            // imgsrc: require("../components/images/pizza.jpeg"),
            price_s: 120,
            price_m: 140,
            price_l: 160,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 19,
            name: "Inverted Cappuccino",
            // imgsrc: require("../components/images/sandwich.jpg"),
            price_s: 120,
            price_m: 140,
            price_l: 160,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 110,
            name: "Hot Chocolate",
            // imgsrc: require("../components/images/tea.jpg"),
            price_s: 120,
            price_m: 140,
            price_l: 160,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 111,
            name: "Cafe Mocha",
            // imgsrc: require("../components/images/tikiya.jpg"),
            price_s: 120,
            price_m: 140,
            price_l: 160,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 112,
            name: "Macchiato",
            // imgsrc: require("../components/images/lemon.jpg"),
            price_s: 80,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 113,
            name: "Flat White",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 120,
            price_m: 140,
            price_l: 160,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 114,
            name: "Cafe Americano",
            // imgsrc: require("../components/images/momos.jpg"),
            price_s: 80,
            price_m: 100,
            price_l: 120,
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 115,
            name: "Eye Opener Espresso",
            // imgsrc: require("../components/images/coffee.jpg"),
            price_s: 60,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 1,
            variety: "Hot-Coffee",
            itemNo: 116,
            name: "Double Espresso",
            // imgsrc: require("../components/images/pizza.jpeg"),
            price_s: 90,
            price_m: "-",
            price_l: "-",
        },
    ],

    // Teas
    [
        {
            varietyNo: 2,
            variety: "Tea",
            itemNo: 21,
            name: "Masala Chai",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 50,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 2,
            variety: "Tea",
            itemNo: 22,
            name: "Green Tea(Tea Bag)",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 100,
            price_m: "-",
            price_l: "-",
        },
    ],

    // Cold-Coffee
    [
        {
            varietyNo: 3,
            variety: "Cold-Coffee",
            itemNo: 31,
            name: "Cold Coffee",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 100,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 3,
            variety: "Cold-Coffee",
            itemNo: 32,
            name: "Choco Frappe",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 3,
            variety: "Cold-Coffee",
            itemNo: 33,
            name: "Caramel Frappe",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 3,
            variety: "Cold-Coffee",
            itemNo: 34,
            name: "Dark Frappe",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 3,
            variety: "Cold-Coffee",
            itemNo: 35,
            name: "Devils Frappe",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 140,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 3,
            variety: "Cold-Coffee",
            itemNo: 36,
            name: "Cold Coffee",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 100,
            price_m: "-",
            price_l: "-",
        },
    ],

    // Ice-Cream
    [
        {
            varietyNo: 4,
            variety: "Ice-Coffee",
            itemNo: 41,
            name: "Ice Americano",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 120,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 4,
            variety: "Ice-Coffee",
            itemNo: 42,
            name: "Ice Espresso",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 100,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 4,
            variety: "Ice-Coffee",
            itemNo: 43,
            name: "Double Shot on Ice",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 120,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 4,
            variety: "Ice-Coffee",
            itemNo: 44,
            name: "Ice Latte",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 100,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 4,
            variety: "Ice-Coffee",
            itemNo: 45,
            name: "Cinnamoan Ice Latte",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 120,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 4,
            variety: "Ice-Coffee",
            itemNo: 46,
            name: "Ice Mocha",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 120,
            price_m: "-",
            price_l: "-",
        },
    ],

    // Shakes/Refreshers
    [
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 51,
            name: "Mango Milkshake",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 52,
            name: "Strwberry Milkshake",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 53,
            name: "Oreo Milkshake",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 54,
            name: "Saffron Milkshake",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 55,
            name: "Vanilla MIlkshake",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 56,
            name: "Kitkat Milkshake",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 57,
            name: "Nutrella Milkshake",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        // {
        //     varietyNo: 5,
        //     variety: "Shakes/Refreshers",
        //     itemNo: 5,
        //     name: "-",
        //     imgsrc: require("../components/images/bread.jpeg"),
        //     price_s: "-",
        //     price_m: "-",
        //     price_l: "-",
        // },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 58,
            name: "Mint Lemonade",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 59,
            name: "Cool Blue",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 510,
            name: "Lemon Ice Tea",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 511,
            name: "Orange Spritzer",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 512,
            name: "Strwberry Splash",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 513,
            name: "Blue Lagoon",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
        {
            varietyNo: 5,
            variety: "Shakes/Refreshers",
            itemNo: 514,
            name: "Nimbu Paani",
            // imgsrc: require("../components/images/bread.jpeg"),
            price_s: 130,
            price_m: "-",
            price_l: "-",
        },
    ],
];

export default Menu_list;
